package:
  name: hdf5
#  version: {{ environ['SIRF_VERSION'] }}
  version: 1.10.1


build:
  preserve_egg_dir: False
  number: 0
    
requirements:
  build:
    #- boost ==1.64.0	
    #- boost-cpp ==1.64.0 
    - boost >=1.63
    - boost-cpp >=1.63
    #- python 
    #- {{ pin_compatible('numpy', max_pin='x.x') }}
#    - python 2.7 # [py27]
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
    #- numpy {{ numpy }}
#    - scipy
#    - matplotlib
#    - docopt
    #- h5py
#    - libxml2
    #- psutil
    - nose
    - coverage
    - fftw
    - swig >=3
#    - libxslt
#    - armadillo
    #- gtest
#    - ismrmrd


  run:
    - boost >=1.63
    - boost-cpp >=1.63
    - fftw
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
