# Language selection
language: cpp python

# Both clang and gcc can be tested. The more is the better.
compiler:
#  - clang
  - gcc

# Cross-operating system test
os:
  - linux
#  - osx

# Environment variables:
global:
 - BUILD_FLAGS="-DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_HDF5=ON -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_Armadillo=ON -DCMAKE_BUILD_TYPE=Release"
  
env:
 - EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_HDF5=ON -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_Armadillo=ON -DCMAKE_BUILD_TYPE=Release"


# Ubuntu 14.04 LTS
dist: trusty

# No need for sudo
sudo: false

# Compilation dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - git-core
      - build-essential
      - g++-5
      - libboost-all-dev
      - libhdf5-serial-dev
      - libfftw3-dev
      - python-dev
      - liblapack-dev
      - libxml2-dev
      - libxslt-dev
      - libarmadillo-dev
      - libace-dev
      - libgtest-dev
      - libplplot-dev
      - root-system-bin

# Actual compilation script

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-cocoa root; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -0 https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz -o cmake-3.7.2-Linux-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzf cmake-3.7.2-Linux-x86_64.tar.gz; fi

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
script:

  - env
  - (export CC=gcc-5; export CXX=g++-5; ./cmake-3.7.2-Linux-x86_64/bin/cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS . )
  - make -j 8 all
  - mv INSTALL/share/gadgetron/config/gadgetron.xml.example INSTALL/share/gadgetron/config/gadgetron.xml
  - export PYTHONPATH=$PYTHONPATH:$PWD/INSTALL/python
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/INSTALL/lib
  - export SIRF_PATH=$PWD/SIRF-SuperBuild/SIRF/
  - PATH=$PWD/bin:$PATH
  - python ./SIRF/src/xSTIR/pSTIR/tests/test1.py
  - gadgetron >& gadgetron.log&
  - python ./SIRF/src/xGadgetron/pGadgetron/tests/fully_sampled.py
  - python ./SIRF/src/xGadgetron/pGadgetron/tests/undersampled.py

  