# Language selection
language: cpp python

# Currently commented out as set with environment flags
# Both clang and gcc can be tested. The more is the better.
#compiler:
#  - clang
#  - gcc

# Cross-operating system test
os:
  - linux
#  - osx

# Environment variables
# Note: On trusty we need to build Armadillo ourselves (the system version is too old)
env:
  global:
    - BUILD_FLAGS="-DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_HDF5=ON -DCMAKE_BUILD_TYPE=Release"
  matrix:
    - EXTRA_BUILD_FLAGS="-DPYTHON_EXECUTABLE=/usr/bin/python3 -DUSE_SSYTEM_SWIG=ON -DUSE_SYSTEM_FFTW3=ON" CC=gcc-5 CXX=g++-5 PYVER=3
    - EXTRA_BUILD_FLAGS=" -DUSE_SSYTEM_SWIG=ON" CC=clang CXX=clang++ PYVER=

# This works as well
# - EXTRA_BUILD_FLAGS=" -DUSE_SSYTEM_SWIG=ON -DUSE_SYSTEM_FFTW3=ON" CC=gcc-5 CXX=g++-5 PYVER=


# Ubuntu 14.04 LTS
dist: trusty

# No need for sudo
sudo: false

# Compilation dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - git-core
      - build-essential
      - g++-5
      - libboost-all-dev
      - libhdf5-serial-dev
      - libfftw3-dev
      - python-dev
      - python3-dev
      - liblapack-dev
      - libxml2-dev
      - libxslt-dev
      - libarmadillo-dev
      - libace-dev
      - libgtest-dev
      - libplplot-dev
      - root-system-bin

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-cocoa root; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -0 https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz -o cmake-3.7.2-Linux-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzf cmake-3.7.2-Linux-x86_64.tar.gz; fi

install:
  - pip${PYVER} install --upgrade pip setuptools wheel
  - pip${PYVER} install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - ./cmake-3.7.2-Linux-x86_64/bin/cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS . 
  - make -j 8
  - mv INSTALL/share/gadgetron/config/gadgetron.xml.example INSTALL/share/gadgetron/config/gadgetron.xml
  
script:

  - export PYTHONPATH=$PYTHONPATH:$PWD/INSTALL/python
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/INSTALL/lib
  - export SIRF_PATH=$PWD/SIRF
  - #env
  - python${PYVER} ./SIRF/src/xSTIR/pSTIR/tests/test1.py
  - ./INSTALL/bin/gadgetron >& gadgetron.log&
  - cat gadgetron.log
  - python${PYVER} ./SIRF/src/xGadgetron/pGadgetron/tests/fully_sampled.py
  - # cat gadgetron.log
  - python${PYVER} ./SIRF/src/xGadgetron/pGadgetron/tests/undersampled.py
  - # cat gadgetron.log
  