# Language selection
# Note: with `language: cpp`, `cache: ccache` works
# but `cache: pip` and `python:` is ignored
language: cpp

# Currently commented out as set with environment flags
# Both clang and gcc can be tested. More is the better.
#compiler:
# - clang
# - gcc

# Environment variables
# Note: On trusty we need to build Armadillo ourselves (the system version is too old)
# Note: altering the matrix here will cause re-building of caches,
# so try to keep this concise to avoid need to update
matrix:
 include:
 # linux g{cc,++}-5 py{27,3}
 - os: linux
   python: 3
   # +fftw3 +hdf5
   env: EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=ON" CC=gcc-5 CXX=g++-5 PYMVER=3
 - os: linux
   python: 2.7
   # +fftw3 +hdf5 +siemens_to_ismrmrd +swig
   env: EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=ON -DBUILD_siemens_to_ismrmrd=ON -DUSE_SYSTEM_SWIG=ON" CC=gcc-5 CXX=g++-5 PYMVER=2
 - os: linux
   python: 3
   # +DEVEL -hdf5 -fftw3 +siemens_to_ismrmrd
   env: EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_FFTW3=OFF -DBUILD_siemens_to_ismrmrd=ON" CC=gcc-5 CXX=g++-5 PYMVER=3
 - os: linux
   python: 2.7
   # +DEVEL -fftw3 -hdf5 -swig
   env: EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DUSE_SYSTEM_FFTW3=OFF -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=OFF" CC=gcc-5 CXX=g++-5 PYMVER=2
 # osx g{cc,++} py{27,36}
 - os: osx
   python: 2.7
   # -hdf5 -swig
   env: EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=OFF" CC=gcc CXX=g++ PYMVER=2
 - os: osx
   # -hdf5 -swig
   python: 3
   env: EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=OFF" CC=gcc CXX=g++ PYMVER=3
 - os: osx
   python: 2.7
   # +DEVEL -hdf5 +swig
   env: EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=ON" CC=gcc CXX=g++ PYMVER=2
 - os: osx
   python: 2.7
   # +DEVEL -fftw3 -hdf5 +swig
   env: EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DUSE_SYSTEM_FFTW3=OFF -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=ON" CC=gcc CXX=g++ PYMVER=2
 # itk
 - os: linux
   python: 3
   # +itk +fftw3 +hdf5
   env: EXTRA_BUILD_FLAGS="-DUSE_ITK=ON -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=ON" CC=gcc-5 CXX=g++-5 PYMVER=3
 - os: osx
   python: 2.7
   # +itk -hdf5 +swig
   env: EXTRA_BUILD_FLAGS="-DUSE_ITK=ON -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=ON" CC=gcc CXX=g++ PYMVER=2
 # docker
 - os: linux
   # +DEVEL +armadillo +fftw3 +hdf5 +siemens_to_ismrmrd +swig
   env: DOCKER_BUILD=1

env:
 global:
  - BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_Boost=ON"
  # don't use too many threads - may crash
  - MAKEFLAGS="-j 2"

# Ubuntu 14.04 LTS
dist: trusty

# sudo required for docker
sudo: required
services:
 - docker

# Compilation dependencies
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - git-core
   - build-essential
   - g++-5
   - libboost-all-dev
   - libhdf5-serial-dev
   - libfftw3-dev
   - python-dev
   - python3-dev
   - python-tk
   - python3-tk
   - liblapack-dev
   - libxml2-dev
   - libarmadillo-dev
   - libgtest-dev
   - libplplot-dev
   - swig
   - ccache
   # not in whitelist
   - libxslt-dev
   - libace-dev
   # - root-system-bin

# cache C/C++/pip
cache:
  - ccache
  - pip

before_install:
 - mkdir -p ~/.local/bin
 - pushd ~/.local/bin
 - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export BUILD_FLAGS="$BUILD_FLAGS -DSHARED_LIBS_ABS_PATH=ON"
      if [ $PYMVER == 2 ]; then
        export PYINST=/System/Library/Frameworks/Python.framework/Versions
        export PY_EXE=$PYINST/$PYMVER.7/bin/python2.7
        export BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PYINST/2.7/lib/libpython2.7.dylib"
        export BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_INCLUDE_DIR=$PYINST/2.7/include/python2.7"
      else
        brew install python3
        export PYINST=/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions
        export PY_EXE=$PYINST/$PYMVER.6/bin/python3.6
        export BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PYINST/3.6/Python"
        export BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_INCLUDE_DIR=$PYINST/3.6/include/python3.6m"
      fi
      export BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_EXECUTABLE=$PY_EXE"
      brew update
      brew tap homebrew/science
      # boost is already installed but 1.65 doesn't work so update
      brew upgrade boost
      # we currently need boost-python
      # brew install boost-python
      brew install ace
      brew install swig
      brew install ccache
      # brew install scipy matplotlib
      # need curl to get more recent cmake
      brew install curl
      curl -0 https://cmake.org/files/v3.8/cmake-3.8.0-Darwin-x86_64.tar.gz -o cmake.tar.gz
      tar xzf cmake.tar.gz
      mv cmake-*/CMake.app/Contents/* cmake-*
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PY_EXE=python$PYMVER
      curl -0 https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz -o cmake.tar.gz
      tar xzf cmake.tar.gz
    fi
 # cmake override
 - pushd cmake-*/bin
 - export PATH="$PWD:$PATH"
 - popd
 # get pip
 - curl -0 https://bootstrap.pypa.io/get-pip.py -o get-pip.py
 - $PY_EXE get-pip.py --user
 # setuptools may be out of date on osx
 - $PY_EXE -m pip install --user -U pip setuptools wheel
 # ensure python bin dir exists (and coverage dependencies installed)
 - $PY_EXE -m pip install --user -U nose codecov coveralls
 # pip path fix
 - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # show lib/site-packages path
      $PY_EXE -m pydoc pip | grep -i -A 1 file
      $PY_EXE -m pydoc codecov | grep -i -A 1 file
      # append python bin dir to path (consult output from previous lines)
      pushd $HOME/Library/Python/$PYMVER*/bin
      export PATH="$PWD:$PATH"
      popd
    fi
 - $PY_EXE --version
 - $PY_EXE -m pip --version
 - $PY_EXE -m pip freeze
 # ccache compiler override
 - ln -s "$(which ccache)" g++
 - ln -s "$(which ccache)" g++-5
 - ln -s "$(which ccache)" gcc
 - ln -s "$(which ccache)" gcc-5
 - export PATH="$PWD:$PATH"
 - popd
 # N.B.: don't put into build matrix to allow caching.
 - export BUILD_FLAGS="$BUILD_FLAGS -DPYVER=$PYMVER"

install:
 - |
    if [[ "$DOCKER_BUILD" == "1" ]]; then
      cd docker
      # pull base image - or not since travis seems to rebuild without cache?
      # TODO: docker save/load (also would help registry uploads/downloads)
      # docker pull ccppetmr/base
      # rebuild base image (using above cache)
      docker-compose build --build-arg UID=1000 --build-arg GROUPS=1000 --pull base
      # build sirf with travis' ccache
      rm -rf devel/.ccache
      mv ~/.ccache devel/
      docker-compose build sirf
      # TODO: why is sudo required here?
      sudo rm -rf devel/.ccache/*
      docker-compose run --rm sirf /bin/bash -c 'sudo cp -R ccache/* /devel/.ccache/'
      mv devel/.ccache ~
    else
      $PY_EXE -m pip install --user --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
      cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS .
      # Job may timeout (>50min) if no ccache, otherwise should be <1min:
      make
      mv INSTALL/share/gadgetron/config/gadgetron.xml.example INSTALL/share/gadgetron/config/gadgetron.xml
      source $PWD/INSTALL/bin/env_ccppetmr.sh
    fi

script:
 - |
    if [[ "$DOCKER_BUILD" == "1" ]]; then
      # push images - but only after tests pass within the container!
      docker login -u $DOCKER_USR -p "$DOCKER_PWD"
      docker-compose run --rm sirf /bin/bash --login -c /devel/test.sh && docker-compose push
    else
      ./INSTALL/bin/gadgetron >& gadgetron.log&
      # print for debugging
      cat builds/SIRF/build/CMakeCache.txt
      ctest -VV
      # print for debugging
      cat builds/SIRF/build/Testing/Temporary/LastTest.log
      # may exceed 4MB travis log limit
      cat gadgetron.log
    fi
