version: '3.2'
services:
 sirf:
  container_name: sirf
  image: ccppetmr/sirf:latest
  environment:
   # mainUser: ${USER:-sirfuser}
   mainUser: sirfuser
   GROUP_ID: ${GROUPS:-1000}
   USER_ID: ${UID:-1000}
  build:
   context: .
   # depends_on:
   #  - core
   cache_from:
    - ccppetmr/sirf:core
    - ccppetmr/sirf:latest
  stdin_open: true
  tty: true
  cap_add:
   - NET_ADMIN
  network_mode: "bridge"
  volumes:
   - ./devel:/devel
 core:
  image: ccppetmr/sirf:core
  build:
   context: .
   dockerfile: Dockerfile-core
   cache_from:
    - ubuntu:16.04
    - ccppetmr/sirf:core
