version: '2.3'
services:
 sirf:
  image: ccppetmr/sirf:service
  restart: unless-stopped
  environment:
   GADGETRON_RELAY_HOST: 0.0.0.0
  runtime: nvidia
  build:
   target: service
   cache_from:
    - ccppetmr/sirf:core
    - ccppetmr/sirf:latest
    - ccppetmr/sirf:service
  ports:
   - "9002:9002"  # gadgetron
   - "9999:8888"  # jupyterhub
