package:
  name: sirf-stir
#  version: {{ environ['SIRF_VERSION'] }}
  version: 1.1.1


build:
  preserve_egg_dir: False
  number: 0
    
requirements:
  build:
    #- boost ==1.64.0	
    #- boost-cpp ==1.64.0 
    - boost >=1.63
#    - boost-cpp
    - python {{ python }}
#    - python 2.7 # [py27]
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
    - numpy {{ numpy }}
#    - scipy
#    - matplotlib
#    - docopt
    - h5py
#    - libxml2
    - psutil
    - nose
    - coverage
    - fftw
    - swig >=3
#    - libxslt
#    - armadillo
    - gtest
#    - ismrmrd


  run:
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - python {{ python }}
    - numpy {{ numpy }}
    - scipy
    - matplotlib
    - docopt
#    - boost >=1.63
#    - h5py
#    - psutil
#    - fftw
#    - libgcc-ng
#    - libstdcxx-ng
#    - openblas
#    - armadillo
#    - gtest
#    - ismrmrd
    - gadgetron
    - h5py
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
