name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # the agent machine operating systems
        os: [ubuntu-latest, ubuntu-18.04]
        EXTRA_BUILD_FLAGS: ["", "-DDEVEL_BUILD=ON"]

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: 
          cd docker;
          sudo bash raw-ubuntu.sh;
          sudo bash build_essential-ubuntu.sh;
          sudo bash build_python-ubuntu.sh;
          sudo bash build_gadgetron-ubuntu.sh;
          sudo bash build_system-ubuntu.sh;
          bash user_python-ubuntu.sh ~/virtualenv python3 ;
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ matrix.type }}
    - name: configure
      shell: bash
      env:
          EXTRA_BUILD_FLAGS: ${{ matrix.EXTRA_BUILD_FLAGS }}
      run: |
          set -ex;
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          export superbuild=`pwd`;
          export BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STIR_WITH_OPENMP=ON -DUSE_SYSTEM_ACE=ON -DUSE_SYSTEM_Armadillo=ON -DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=ON -DUSE_ITK=ON -DBUILD_siemens_to_ismrmrd=ON -DUSE_SYSTEM_SWIG=ON -DCMAKE_INSTALL_PREFIX=~/install -DPYVER=3";
          mkdir -p build/;
          cd build;
          export CC="gcc-7";
          export CXX="g++-7";
          source ~/virtualenv/bin/activate;
          cmake -S ${GITHUB_WORKSPACE} ${BUILD_FLAGS} ${EXTRA_BUILD_FLAGS} ;
    - name: build
      shell: bash
      run: 
          cd ${GITHUB_WORKSPACE}/build;
          source ~/virtualenv/bin/activate;
          cmake --build . -j 2;
    - name: tests
      shell: bash
      run: 
          bash docker/ctest_sirf.sh
